### PR TITLE
Cleaning up readme, keyword matching, and compiler errors

### PR DESCRIPTION
**Pull request by dagrooms52**
- Fixed a few typos in the readme.md.
- Simplified keyword matching to reduce assignment operations in Scorpion/assemmbler/Assembler.cpp.
- Compiled Scorpion/assemmbler/Assembler.cpp with g++ and fixed several errors.

### CODE REVIEW

**Comment by AndroDevcd** [comment]
Hey, thanks for the update. I would merge, but herr is the problem. I have updated a ton of compiler errors and have yet to commit. When i get home today and commit it (around 8pm) i will go in your branch and extract the canges you made and we can go from there.

Also, i am having trouble with making a much faster bytecode for my vm. I will create a bytecode-feadme file and explain tje current bytecode my vm runs on and then maybe you can help me make it simpler. Just take to note: THE SHORTER THE BYTECODE...THE FASTER THE EXECUTION TIME.

Thank you.

**Comment by AndroDevcd** [comment]
Also sorry for my bad spelling haha

**Comment by AndroDevcd** [comment]
Oh, I almost forgot, I am creating a wiki and could also use help in that as well

**Comment by dagrooms52** [comment]
I'd love to help on anything you think needs focus, but I've never coded anything similar to this project, so I was going to do some code cleanup and testing until I get a feel for what's going on.

**Comment by AndroDevcd** [comment]
Ok well in the meantime just review the code and definitely check out my wiki, I think it will really help. Also thank you for your help.

**Comment by dagrooms52** [comment]
Check this out: https://github.com/github/linguist/issues/2452

**Comment by AndroDevcd** [comment]
Thanks for the heads up, Ill talk to him tomorrow. Also, by tomorrow night, I would have extracted your updates from the commit request and then go from there.

**Comment by AndroDevcd** [comment]
I have extracted your updates and we are ready to move forward. Sorry for it taking so long, I have really been trying to make the Scorpion virtual machine faster.

**Pull request closed without merging**
